name: sublime-text-3
version: '3143'
summary: A sophisticated text editor for code, markup and prose.
description: |
  A sophisticated text editor for code, markup and prose.

grade: stable
confinement: classic

apps:
  subl:
    command: sublime_text
    desktop: sublime_text.desktop

parts:
  sublime-text-3:
    plugin: dump
    source: https://download.sublimetext.com/sublime_text_3_build_$SNAPCRAFT_PROJECT_VERSION_x64.tar.bz2
    install: |
      sed -i 's|Icon=.*|Icon=/Icon/48x48/sublime-text.png|g' $SNAPCRAFT_PART_INSTALL/sublime_text.desktop
