name: sublime-text
version: "4173"
summary: A sophisticated text editor for code, markup and prose.
title: Sublime Text
description: |
  Sublime Text is a powerful multi-platform text editor with a clean, modern user interface.
  Bringing wide support for programming languages, extensions, syntax-based features and many other useful features alongside low resource usage, Sublime Text proves itself to be a very competent solution for a vast set of environments and applications.
  The software may be downloaded and evaluated for free, however a license must be purchased for continued use.

    **Authors**
  
  This snap is maintained by the Snapcrafters community, and is not necessarily endorsed or officially maintained by the upstream developers.
contact: https://github.com/snapcrafters/sublime-text/issues
issues: https://github.com/snapcrafters/sublime-text/issues
website: https://www.sublimetext.com/
license: Proprietary

# Do not rev to core22. The upstream binary appears to be built on/against Ubuntu 20.04
# so moving to core22 will likely break this, as the new core will ship newer incompatible
# libc - as seen in issue #47
base: core20
architectures:
  - build-on: arm64
  - build-on: amd64

grade: stable
confinement: classic
compression: lzo

apps:
  subl:
    command: opt/sublime_text/sublime_text
    desktop: usr/share/applications/sublime_text.desktop

parts:
  sublime-text:
    source: https://download.sublimetext.com/sublime-text_build-$SNAPCRAFT_PROJECT_VERSION_$SNAPCRAFT_TARGET_ARCH.deb
    plugin: dump
    override-build: |
      snapcraftctl build
      # Correct icon path
      sed -i 's|Icon=sublime-text|Icon=usr/share/icons/hicolor/256x256/apps/sublime-text.png|' $SNAPCRAFT_PART_INSTALL/usr/share/applications/sublime_text.desktop

      # Desktop Action are not Unity specific.
      sed -i 's|OnlyShowIn|#OnlyShowIn|g' $SNAPCRAFT_PART_INSTALL/usr/share/applications/sublime_text.desktop
    stage-packages:
      - libbsd0
      - libffi7
      - libgtk-3-0
      - libpcre3
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
    build-attributes:
      - no-patchelf
